FROM python:3.11-slim

RUN apt-get update && apt-get install -y zfsutils-linux && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY unlock-service.py .
RUN chmod +x unlock-service.py
RUN pip install flask werkzeug --no-cache-dir

CMD ["python3", "unlock-service.py"]

