name: Build and Deploy

on:
  push:
    tags: ['v*']  # Only build on tag push, not every commit to main
  workflow_dispatch:

jobs:
  build-llm-router:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/llm-router
      app_path: apps/homelab-ai
      dockerfile: llm-router/Dockerfile
      context: llm-router
    secrets: inherit

  build-dashboard:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/local-ai-dashboard
      app_path: apps/homelab-ai
      dockerfile: dashboard/Dockerfile
      context: dashboard
    secrets: inherit

  build-llm-manager:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/llm-manager
      app_path: apps/homelab-ai
      dockerfile: llm-manager/Dockerfile
      context: llm-manager
    secrets: inherit

  build-image-server:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/image-server
      app_path: apps/homelab-ai
      dockerfile: image-server/Dockerfile
      context: image-server
    secrets: inherit

  build-tts-server:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/tts-server
      app_path: apps/homelab-ai
      dockerfile: tts-server/Dockerfile
      context: tts-server
    secrets: inherit

  build-agent-harness:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/agent-harness
      app_path: apps/homelab-ai
      dockerfile: claude-harness/Dockerfile
      context: claude-harness
    secrets: inherit

  deploy:
    needs: [build-llm-router, build-dashboard, build-llm-manager, build-image-server, build-tts-server, build-agent-harness]
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write SSH key
          printf '%s\n' "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # Add server to known hosts
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

          # Test SSH connection
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/deploy_key -p ${{ secrets.DEPLOY_PORT }} -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo 'SSH connection successful'" || {
            echo "SSH connection failed. Check secrets: DEPLOY_SSH_KEY, DEPLOY_HOST, DEPLOY_PORT, DEPLOY_USER"
            exit 1
          }

      - name: Deploy homelab-ai
        env:
          SSH_KEY: ~/.ssh/deploy_key
          SSH_USER: ${{ secrets.DEPLOY_USER }}
          SSH_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          APP_PATH="/home/unarmedpuppy/server/apps/homelab-ai"

          # Pull latest images and restart
          ssh -i $SSH_KEY -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \
            "cd $APP_PATH && sudo docker compose pull && sudo docker compose up -d"

          echo 'Deployment complete!'
