name: Build and Deploy

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-llm-router:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/llm-router
      app_path: apps/homelab-ai
      dockerfile: llm-router/Dockerfile
      context: llm-router
    secrets: inherit

  build-dashboard:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/local-ai-dashboard
      app_path: apps/homelab-ai
      dockerfile: dashboard/Dockerfile
      context: dashboard
    secrets: inherit

  build-llm-manager:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/llm-manager
      app_path: apps/homelab-ai
      dockerfile: llm-manager/Dockerfile
      context: llm-manager
    secrets: inherit

  build-image-server:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/image-server
      app_path: apps/homelab-ai
      dockerfile: image-server/Dockerfile
      context: image-server
    secrets: inherit

  build-tts-server:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/tts-server
      app_path: apps/homelab-ai
      dockerfile: tts-server/Dockerfile
      context: tts-server
    secrets: inherit

  build-claude-harness:
    uses: unarmedpuppy/workflows/.gitea/workflows/docker-build.yml@main
    with:
      image_name: library/claude-harness
      app_path: apps/homelab-ai
      dockerfile: claude-harness/Dockerfile
      context: claude-harness
    secrets: inherit
