version: '3.1'

services:
  tailscale:
    image: tailscale/tailscale:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-volume:/var/lib/tailscale
    command: ["tailscaled"]


volumes:
  tailscale-volume: