#!/usr/bin/env python3
"""
Create Plex playlists from organized music files.

This script:
1. Reads playlist mappings from organize_music_for_plex.py output
2. Finds tracks in Plex library
3. Creates playlists in Plex
"""

import os
import sys
import json
from pathlib import Path
from typing import List, Dict, Optional

try:
    from plexapi.server import PlexServer
    from plexapi.playlist import Playlist
except ImportError:
    print("ERROR: plexapi not installed. Run: pip install plexapi")
    sys.exit(1)


# Configuration
PLEX_URL = os.getenv("PLEX_URL", "http://192.168.86.47:32400")
PLEX_TOKEN = os.getenv("PLEX_TOKEN", "")
PLAYLIST_MAPPINGS_FILE = "playlist_mappings.json"  # Generated by organize_music_for_plex.py


class PlexPlaylistCreator:
    """Create playlists in Plex from file mappings."""
    
    def __init__(self, plex_url: str, plex_token: str):
        if not plex_token:
            raise ValueError("Plex token required. Set PLEX_TOKEN environment variable")
        
        self.plex = PlexServer(plex_url, plex_token)
        self.music_library = None
        
        # Find music library
        for library in self.plex.library.sections():
            if library.type == 'artist':
                self.music_library = library
                break
        
        if not self.music_library:
            raise ValueError("Music library not found in Plex")
    
    def find_track_by_path(self, file_path: str) -> Optional:
        """Find a track in Plex library by file path."""
        # Plex uses internal paths, so we need to search by metadata
        # This is a simplified version - may need adjustment
        
        # Extract artist/album/track from path
        path_parts = Path(file_path).parts
        if len(path_parts) >= 3:
            artist_name = path_parts[-3]
            album_name = path_parts[-2]
            track_name = Path(path_parts[-1]).stem
            
            # Try to find by artist
            try:
                artist = self.music_library.get(artist_name)
                if artist:
                    # Find album
                    for album in artist.albums():
                        if album.title == album_name:
                            # Find track
                            for track in album.tracks():
                                if track_name in track.title or track.title in track_name:
                                    return track
            except Exception:
                pass
        
        return None
    
    def find_track_by_metadata(self, artist: str, title: str, album: str = None) -> Optional:
        """Find a track in Plex library by metadata."""
        try:
            # Search for artist
            results = self.music_library.search(artist, libtype='artist')
            if not results:
                return None
            
            artist_obj = results[0]
            
            # Find album
            if album:
                album_obj = None
                for alb in artist_obj.albums():
                    if alb.title.lower() == album.lower():
                        album_obj = alb
                        break
                
                if album_obj:
                    # Find track in album
                    for track in album_obj.tracks():
                        if title.lower() in track.title.lower() or track.title.lower() in title.lower():
                            return track
            else:
                # Search all tracks by artist
                for track in artist_obj.tracks():
                    if title.lower() in track.title.lower() or track.title.lower() in title.lower():
                        return track
            
        except Exception as e:
            print(f"  ⚠ Error finding track {artist} - {title}: {e}")
        
        return None
    
    def create_playlist(self, playlist_name: str, tracks: List) -> Optional[Playlist]:
        """Create a playlist in Plex."""
        if not tracks:
            print(f"  ⚠ No tracks found for playlist: {playlist_name}")
            return None
        
        try:
            # Check if playlist already exists
            existing = self.plex.playlists()
            for pl in existing:
                if pl.title == playlist_name:
                    print(f"  ⚠ Playlist already exists: {playlist_name}")
                    return pl
            
            # Create new playlist
            playlist = self.plex.createPlaylist(playlist_name, items=tracks)
            print(f"  ✓ Created playlist: {playlist_name} ({len(tracks)} tracks)")
            return playlist
            
        except Exception as e:
            print(f"  ✗ Error creating playlist {playlist_name}: {e}")
            return None
    
    def create_playlists_from_mappings(self, mappings_file: str) -> None:
        """Create playlists from playlist mappings file."""
        if not Path(mappings_file).exists():
            print(f"✗ Playlist mappings file not found: {mappings_file}")
            print("  Run organize_music_for_plex.py first to generate this file")
            return
        
        with open(mappings_file, 'r') as f:
            mappings = json.load(f)
        
        print("=" * 60)
        print("Creating Plex Playlists")
        print("=" * 60)
        print(f"Found {len(mappings)} playlist(s)\n")
        
        total_tracks = 0
        created_playlists = 0
        
        for playlist_name, file_paths in mappings.items():
            print(f"\n📁 Processing: {playlist_name}")
            print(f"  Found {len(file_paths)} file(s)")
            
            tracks = []
            found = 0
            not_found = 0
            
            for file_path in file_paths:
                # Try to find track
                track = self.find_track_by_path(file_path)
                if not track:
                    # Fallback: try to parse metadata from path
                    path_parts = Path(file_path).parts
                    if len(path_parts) >= 3:
                        artist = path_parts[-3]
                        track_name = Path(path_parts[-1]).stem
                        # Remove track number prefix if present
                        if ' - ' in track_name:
                            track_name = track_name.split(' - ', 1)[1]
                        
                        track = self.find_track_by_metadata(artist, track_name)
                
                if track:
                    tracks.append(track)
                    found += 1
                else:
                    not_found += 1
                    print(f"    ⚠ Not found: {Path(file_path).name}")
            
            if tracks:
                playlist = self.create_playlist(playlist_name, tracks)
                if playlist:
                    created_playlists += 1
                    total_tracks += len(tracks)
            else:
                print(f"  ✗ No tracks found for playlist: {playlist_name}")
        
        print("\n" + "=" * 60)
        print("Summary")
        print("=" * 60)
        print(f"Playlists created: {created_playlists}/{len(mappings)}")
        print(f"Total tracks added: {total_tracks}")


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Create Plex playlists from organized music files"
    )
    parser.add_argument(
        '--mappings',
        default=PLAYLIST_MAPPINGS_FILE,
        help=f"Playlist mappings file (default: {PLAYLIST_MAPPINGS_FILE})"
    )
    parser.add_argument(
        '--plex-url',
        default=PLEX_URL,
        help=f"Plex server URL (default: {PLEX_URL})"
    )
    parser.add_argument(
        '--plex-token',
        default=PLEX_TOKEN,
        help="Plex authentication token (or set PLEX_TOKEN env var)"
    )
    
    args = parser.parse_args()
    
    if not args.plex_token:
        print("ERROR: Plex token required")
        print("  Set PLEX_TOKEN environment variable or use --plex-token")
        print("  Get token from: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/")
        sys.exit(1)
    
    try:
        creator = PlexPlaylistCreator(args.plex_url, args.plex_token)
        creator.create_playlists_from_mappings(args.mappings)
    except Exception as e:
        print(f"✗ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()

